### PR TITLE
Tram lint

### PR DESCRIPTION
**Pull request by JRJurman**
## Summary
Now that we have an eslint-config for Tram-One, lets use it!  
Also fixed package-lock.json issues

## Tests
- [x] local tests pass

### CODE REVIEW

**Comment by chtinahow** [comment]
image
The linter doesn't work

**Comment by chtinahow** [comment]
❌  Don't merge it! ❌

**Review by chtinahow — CHANGES_REQUESTED** [review]
❌  don't merge ❌  
image

**Comment by JRJurman** [comment]
@chtinahow Fixed lint issues, added circleci config, but I don't believe that will be picked up on this PR

**Review by chtinahow — APPROVED** [review]
Ran and Looks good to me 👍

**Pull request merged**
